name: TNS-Parkour
version: ${project.version}
main: com.github.thedeathlycow.tnsparkour.TnsParkour
api-version: 1.17
authors: [ TheDeathlyCow ]
description: Provides a basic framework for parkour on TNS, and integrates with modular minigames datapack.
website: github.com/thedeathlycow/tns-parkour
